### ISSUE TITLE
关于Task2数据集的疑问

### ISSUE THREAD

**Issue by huyjj** [JunlinHan/BID#1]
你好，我想请问您在Task2中，为什么在叠加雨、雾、雪、雨滴等图层时，要将图像先加上一再除二？我实验后似乎不能得到与论文中类似的图像，但如果不采用这一步骤则可以得到类似的图像。

**Comment by JunlinHan** [comment]
Hi,
Oh that's just a conversion. The default range is -1-1 (I didn't modify it), add 1 then divide 2 converts the range back to 0-1.

hi 你好, 
感谢对我们工作的关注啊。-1 - 1 是默认的范围，加上1再除以2只是为了把范围调整到0-1.

**Comment by JunlinHan** [comment]
另: 第150行的注释有稍微提到这个。
Default normalization makes data between [-1,1], we scale some of them to [0,1] for adding rain components.

**Comment by huyjj** [comment]
非常感谢您的耐心回复！我下次一定好好看注释！
