### ISSUE TITLE
Question about model inference

### ISSUE THREAD

**Issue by nataliameira** [JunlinHan/BID#6]
Hi @JunlinHan,

When performing the test with the following command:

`python test.py --dataroot ./datasets/raina --name task2a --model raina --dataset_mode raina --test_input B`

`--test_input B` means I'm only testing with the rain noise cases? Use only the weight of that specific case?

(I'm sorry for this primary question, I would really like to understand about your project)

Thank you!

**Comment by JunlinHan** [comment]
Yes! test_input will control the testing cases. The mode is identical for all cases (model is able to handle all possible cases). 

Hope it helps!
