### ISSUE TITLE
Image size in test stage

### ISSUE THREAD

**Issue by zhenyuan1234** [JunlinHan/BID#8]
In the test stage, the size of the output image is 256*256, how to set the size of the output image to the original size?

**Comment by JunlinHan** [comment]
You can check options here: 
![图片](https://github.com/JunlinHan/BID/assets/48272064/2548477a-038f-4258-a07d-b5022caae288)
Try adding --preprocess none!

**Comment by zhenyuan1234** [comment]
Thank you for the response!
We have modified --preprocess none, but the following error still occurs. I want to change the size of the output image to 720*480, can you tell me how to do it, thanks!


self.real_input = torch.from_numpy(temp.reshape(1, 3, self.width, self.width))  line 190, in forward
ValueError: cannot reshape array of size 1036800 into shape (1,3,256,256)


| |
yjqiao58
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 10/1/2023 06:06 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [JunlinHan/BID] Image size in test stage (Issue #8) |

You can check options here:

Try adding --preprocess none!
